import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header, Navigation} from "@/app/components";
import ReactQueryClientProvider from './config/ReactQueryClientProvider';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <ReactQueryClientProvider>
                <Header/>
                <div className={'w-full flex gap-4'}>
                    <Navigation/>
                    {children}
                </div>
            </ReactQueryClientProvider>
        </body>
        </html>
    );
}
